    spaces:
      - space_id: 11d526bf-2d47-4131-96a5-2d8c820de4ef
        region:
          - 1071
          - 519
          - 1692
          - 436
          - 1266
          - 271
          - 744
          - 341
